# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ags_data_summry_plots
                                 A QGIS plugin
 AGS data summary plots
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-02-21
        copyright            : (C) 2026 by Amageo Limited
        email                : tony.daly@amageo.co.uk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Amageo Limited'
__date__ = '2026-02-21'
__copyright__ = '(C) 2026 by Amageo Limited'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ags_data_summry_plots class from file ags_data_summry_plots.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .AGS_data_summary_plots import ags_data_summry_plotsPlugin
    return ags_data_summry_plotsPlugin()
