# -*- coding: utf-8 -*-

"""
/***************************************************************************
 ags_data_summry_plots
                                 A QGIS plugin
 AGS data summary plots
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-02-21
        copyright            : (C) 2026 by Amageo Limited
        email                : tony.daly@amageo.co.uk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Amageo Limited'
__date__ = '2026-02-21'
__copyright__ = '(C) 2026 by Amageo Limited'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (QgsProcessing,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFile,
                       QgsProcessingParameterFolderDestination,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFeatureSink)

import sqlite3
import webbrowser

import numpy as np
import pandas as pd
import plotly.express as px
import plotly.io as pio


class ags_data_summry_plotsAlgorithm(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT = 'OUTPUT'
    INPUT = 'INPUT'

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        # We add the input vector features source. It can have any kind of
        # geometry.
        self.addParameter(
            QgsProcessingParameterFile(
                self.INPUT,
                self.tr('GeoPackage file')
            )
        )

        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).
        self.addParameter(
            QgsProcessingParameterFolderDestination(
                self.OUTPUT,
                self.tr('Output folder')
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        """
        Summary of data plots.
        The following plots will be generated if the data is available:
        1. SPT vs Depth
        2. WC vs Depth
        3. LL vs PL
        """
        database = parameters['INPUT']
        dst = parameters['OUTPUT']
        # TODO access geopackage using sqlite3
        conn = sqlite3.connect(database)
        cur = conn.cursor()
        cur.execute('select * from ISPT where LOCA_ID = "BH504"')
        rows = cur.fetchall()
    
        for row in rows:
            feedback.pushInfo(f"Result={row}")
    
        # =================SPT -Depth==================================
        # create dataframe - link geology codes
    
        qry = """select ISPT.LOCA_ID, ISPT_TOP, (ISPT_TOP + (ISPT_NPEN/1000))
            as ISPT_BASE, ISPT_NVAL, ISPT_REP, GEOL_GEOL
            from ISPT left join GEOL ON ISPT.LOCA_ID = GEOL.LOCA_ID
            where ISPT_TOP >= GEOL_TOP AND ISPT_BASE <= GEOL.GEOL_BASE
            order by GEOL_GEOL"""
        df = pd.read_sql_query(qry, conn)
    
        feedback.pushInfo(f"Result = {df}")
    
        # need to plot nulls as 50 where non full penetration
        # reported result visble in hover
        df["ISPT_NVAL"] = df["ISPT_NVAL"].fillna(50)
    
        # create plot (matplotlib)
        pio.templates.default = "plotly_white"
    
        # Create SPT vs depth multi plots
        fig = px.scatter(
            df,
            x='ISPT_NVAL',
            y='ISPT_TOP',
            height=1600,
            facet_col='GEOL_GEOL',
            color='LOCA_ID',
            labels={"ISPT_NVAL": "SPT 'N' value",
                    "ISPT_TOP": "Depth (mbgl)",
                    "GEOL_GEOL": "Geology code",
                    "LOCA_ID": "EXPL Hole",
                    "ISPT_REP": "Reported value"
                    },
            title="SPT vs Depth by geology code (GEOL_GEOL)",
            hover_data=["ISPT_REP"],
            facet_col_wrap=4
        )
        fig.update_layout(xaxis_range=[0, 55])
        fig.update_layout(yaxis_range=[0, 35])
        fig.update_layout(showlegend=True)
        fig.update_xaxes(showgrid=True, gridwidth=1, gridcolor='DarkGray')
        fig.update_yaxes(showgrid=True, gridwidth=1, gridcolor='DarkGray')
        fig.update_traces(marker=dict(size=12,
                                      line=dict(width=2,
                                                color='DarkSlateGrey')),
                          selector=dict(mode='markers'))
        fig.update_yaxes(autorange='reversed')
        fig.update_layout(paper_bgcolor='#CFDBDF')
        fig.for_each_xaxis(lambda x: x.update(showticklabels=True))
        fig.show()
        fig.write_html(dst+'/'+'SPTvsDepth.html')
    
        # =================SPT -Elevation==================================
        # create dataframe - link geology codes
        qry = """select SUB.LOCA_ID, ISPT_TOP, ISPT_BASE,
            ISPT_NVAL, ISPT_REP, GEOL_GEOL, (LOCA_GL - ISPT_TOP)
            as ISPT_ELEV, LOCA_GL
            from
            (select ISPT.LOCA_ID, ISPT_TOP, (ISPT_TOP + (ISPT_NPEN/1000))
            as ISPT_BASE, ISPT_NVAL, ISPT_REP, GEOL_GEOL
            from ISPT left join GEOL ON ISPT.LOCA_ID = GEOL.LOCA_ID
            where ISPT_TOP >= GEOL_TOP AND ISPT_BASE <= GEOL.GEOL_BASE) as SUB
            left join LOCA on SUB.LOCA_ID = LOCA.LOCA_ID
            order by GEOL_GEOL"""
        df = pd.read_sql_query(qry, conn)
        feedback.pushInfo(f"Result = {df}")
    
        # Plot nulls as 50 where non full pen reported result visble in hover
        df["ISPT_NVAL"] = df["ISPT_NVAL"].fillna(50)
    
        # create plot (matplotlib)
        pio.templates.default = "plotly_white"
    
        # Create SPT vs depth multi plots
        fig = px.scatter(
            df,
            x='ISPT_NVAL',
            y='ISPT_ELEV',
            height=1600,
            facet_col='GEOL_GEOL',
            color='LOCA_ID',
            labels={"ISPT_NVAL": "SPT 'N' value",
                    "ISPT_ELEV": "Elevation (mAOD)",
                    "GEOL_GEOL": "Geology code",
                    "LOCA_ID": "EXPL Hole",
                    "ISPT_REP": "Reported value"
                    },
            title="SPT vs Elevation by geology code (GEOL_GEOL)",
            hover_data=["ISPT_REP"],
            facet_col_wrap=4
        )
        fig.update_layout(xaxis_range=[0, 55])
        fig.update_layout(yaxis_range=[10, 60])
        fig.update_layout(showlegend=True)
        fig.update_xaxes(showgrid=True, gridwidth=1, gridcolor='DarkGray')
        fig.update_yaxes(showgrid=True, gridwidth=1, gridcolor='DarkGray')
        fig.update_traces(marker=dict(size=12,
                                      line=dict(width=2,
                                                color='DarkSlateGrey')),
                          selector=dict(mode='markers'))
        fig.update_layout(paper_bgcolor='#CFDBDF')
        fig.for_each_xaxis(lambda x: x.update(showticklabels=True))
        fig.show()
        fig.write_html(dst+'/'+'SPTvsElecation.html')
    
        # ======================MOISTURE CONYENT vs Depth===========================
    
        # create dataframe - link geology codes
        qry = """select LNMC.LOCA_ID, SAMP_TOP, LNMC_MC, GEOL_GEOL
            from LNMC left join GEOL on LNMC.LOCA_ID = GEOL.LOCA_ID
            where SAMP_TOP >= GEOL_TOP and SAMP_TOP < GEOL_BASE
            order by GEOL_GEOL"""
        df = pd.read_sql_query(qry, conn)
        feedback.pushInfo(f"Result = {df}")
    
        # create plot (matplotlib)
        pio.templates.default = "plotly_white"
    
        # Create WC vs depth multi plots
        fig = px.scatter(
            df,
            x='LNMC_MC',
            y='SAMP_TOP',
            height=1600,
            facet_col='GEOL_GEOL',
            color='LOCA_ID',
            labels={"LNMC_MC": "Water content(%)",
                    "SAMP_TOP": "Depth (mbgl)",
                    "GEOL_GEOL": "Geology code",
                    "LOCA_ID": "EXPL Hole"},
            title="Water content vs Depth by geology code (GEOL_GEOL)",
            facet_col_wrap=4
        )
        fig.update_layout(xaxis_range=[0, 110])
        fig.update_layout(yaxis_range=[0, 35])
        fig.update_layout(showlegend=True)
        fig.update_xaxes(showgrid=True, gridwidth=1, gridcolor='DarkGray')
        fig.update_yaxes(showgrid=True, gridwidth=1, gridcolor='DarkGray')
        fig.update_traces(marker=dict(size=12,
                                      line=dict(width=2,
                                                color='DarkSlateGrey')),
                          selector=dict(mode='markers'))
        fig.update_yaxes(autorange='reversed')
        fig.update_layout(paper_bgcolor='#CFDBDF')
        fig.for_each_xaxis(lambda x: x.update(showticklabels=True))
        fig.show()
        fig.write_html(dst+'/'+'WaterContentvsDepth.html')
    
        # ======================MOISTURE CONYENT DIST=============================
    
        # create dataframe - link geology codes
        qry = """SELECT LNMC_MC, count(LNMC_MC) as count, GEOL_GEOL
            from (select LNMC.LOCA_ID, SAMP_TOP, LNMC_MC, GEOL_GEOL from LNMC
            left join GEOL on LNMC.LOCA_ID = GEOL.LOCA_ID
            where SAMP_TOP >= GEOL_TOP AND SAMP_TOP < GEOL_BASE)
            group by LNMC_MC, GEOL_GEOL order by GEOL_GEOL"""
        df = pd.read_sql_query(qry, conn)
    
        feedback.pushInfo(f"Result = {df}")
    
        # create plot (matplotlib)
        pio.templates.default = "plotly_white"
    
        # Create WC vs depth multi plots
        fig = px.bar(
            df,
            x='LNMC_MC',
            y='count',
            height=1600,
            facet_row='GEOL_GEOL',
            color='GEOL_GEOL',
            labels={"LNMC_MC": "Water content(%)",
                    # "SAMP_TOP": "Depth (mbgl)",
                    "GEOL_GEOL": "Geology code",
                    # "LOCA_ID": "EXPL Hole"},
                    },
            title="Water content distribution by geology code (GEOL_GEOL)",
            facet_col_wrap=2
        )
        fig.update_xaxes(showgrid=True, gridwidth=1, gridcolor='DarkGray')
        fig.update_yaxes(showgrid=True, gridwidth=1, gridcolor='DarkGray')
        # fig.update_traces(marker=dict(size=12,
        #                           line=dict(width=2,
        #                                     color='DarkSlateGrey')),
        #               selector=dict(mode='markers'))
        # fig.update_yaxes(autorange='reversed')
        fig.update_layout(paper_bgcolor='#CFDBDF')
        fig.for_each_xaxis(lambda x: x.update(showticklabels=True))
        fig.show()
        fig.write_html(dst+'/'+'WaterContentDist.html')
    
        # =========================UNDRAINED COHESION=====================
    
        # create dataframe - link geology codes
        qry = """select TRIT.LOCA_ID, SAMP_TOP, TRIT_CU, GEOL_GEOL
            from TRIT left join GEOL on TRIT.LOCA_ID = GEOL.LOCA_ID
            where SAMP_TOP >= GEOL_TOP and SAMP_TOP < GEOL_BASE
            order by GEOL_GEOL"""
        df = pd.read_sql_query(qry, conn)
        feedback.pushInfo(f"Result = {df}")
    
        # create plot (matplotlib)
        pio.templates.default = "plotly_white"
    
        # Create WC vs depth multi plots
        fig = px.scatter(
            df,
            x='TRIT_CU',
            y='SAMP_TOP',
            height=1600,
            facet_col='GEOL_GEOL',
            color='LOCA_ID',
            labels={"TRIT_CU": "Undrained Cohesion (kN/m2)",
                    "SAMP_TOP": "Depth (mbgl)",
                    "GEOL_GEOL": "Geology code",
                    "LOCA_ID": "EXPL Hole"},
            title="Undrained cohesion vs Depth by geology code (GEOL_GEOL)",
            facet_col_wrap=4
        )
        fig.update_layout(xaxis_range=[0, 400])
        fig.update_layout(yaxis_range=[0, 35])
        fig.update_layout(showlegend=True)
        fig.update_xaxes(showgrid=True, gridwidth=1, gridcolor='DarkGray')
        fig.update_yaxes(showgrid=True, gridwidth=1, gridcolor='DarkGray')
        fig.update_traces(marker=dict(size=12,
                                      line=dict(width=2,
                                                color='DarkSlateGrey')),
                          selector=dict(mode='markers'))
        fig.update_yaxes(autorange='reversed')
        fig.update_layout(paper_bgcolor='#CFDBDF')
        fig.for_each_xaxis(lambda x: x.update(showticklabels=True))
        fig.show()
        fig.write_html(dst+'/'+'UndrainedCohesionvsDepth.html')
    
        # =========================PLASTICITY=====================
    
        # create dataframe - link geology codes
        qry = """select LLPL.LOCA_ID, SAMP_TOP, LLPL_LL, LLPL_PL,
            (LLPL_LL-LLPL_PL) as IP, GEOL_GEOL from LLPL left join GEOL
            on LLPL.LOCA_ID = GEOL.LOCA_ID
            where SAMP_TOP >= GEOL_TOP AND SAMP_TOP < GEOL_BASE
            order by GEOL_GEOL"""
        df = pd.read_sql_query(qry, conn)
        feedback.pushInfo(f"Result = {df}")
        lst_GEOL_GEOL = df['GEOL_GEOL'].unique()
    
        # create plot (matplotlib)
        pio.templates.default = "plotly_white"
    
        # Create WC vs depth multi plots
        fig = px.scatter(
            df,
            x='LLPL_LL',
            y='IP',
            height=1600,
            facet_row='GEOL_GEOL',
            color='LOCA_ID',
            labels={"LLPL_LL": "Liquid Limit (%)",
                    "LLPL_PL": "Plastic Limit (%)",
                    "IP": "Plasticity Index (%)",
                    "GEOL_GEOL": "Code",
                    "LOCA_ID": "EXPL Hole"},
            title="Plasticity by geology code (GEOL_GEOL)",
            hover_data=["LLPL_PL"],
        )
        col = 1
        for row in range(1, len(lst_GEOL_GEOL)+1):
            feedback.pushInfo(f"Row = {row}")
            fig.add_annotation(x=35, y=27, text='CL',
                               xref=f'x{col}', yref=f'y{row}', showarrow=False)
            fig.add_annotation(x=60, y=45, text='CH',
                               xref=f'x{col}', yref=f'y{row}', showarrow=False)
            fig.add_annotation(x=80, y=55, text='CV',
                               xref=f'x{col}', yref=f'y{row}', showarrow=False)
            fig.add_shape(type="circle", x0=32, y0=24, x1=38, y1=30,
                          xref=f'x{col}', yref=f'y{row}',
                          line=dict(color="black", width=1))
            fig.add_shape(type="circle", x0=57, y0=42, x1=63, y1=48,
                          xref=f'x{col}', yref=f'y{row}',
                          line=dict(color="black", width=1))
            fig.add_shape(type="circle", x0=77, y0=52, x1=83, y1=58,
                          xref=f'x{col}', yref=f'y{row}',
                          line=dict(color="black", width=1))
            fig.add_shape(type="line", x0=10, x1=26, y0=6, y1=6,
                          xref=f'x{col}', yref=f'y{row}',
                          line=dict(color="black", width=1))
            fig.add_shape(type="line", x0=26, x1=115, y0=6, y1=70,
                          xref=f'x{col}', yref=f'y{row}',
                          line=dict(color="black", width=1))
            fig.add_shape(type="line", x0=50, x1=50, y0=0, y1=70,
                          xref=f'x{col}', yref=f'y{row}',
                          line=dict(color="black", width=1))
            fig.add_shape(type="line", x0=70, x1=70, y0=0, y1=70,
                          xref=f'x{col}', yref=f'y{row}',
                          line=dict(color="black", width=1))
    
        fig.update_layout(xaxis_range=[0, 120])
        fig.update_layout(yaxis_range=[0, 70])
        fig.update_layout(showlegend=True)
        fig.update_xaxes(showgrid=True, gridwidth=1, gridcolor='DarkGray')
        fig.update_yaxes(showgrid=True, gridwidth=1, gridcolor='DarkGray')
        fig.update_traces(marker=dict(size=12,
                                      line=dict(width=2,
                                                color='DarkSlateGrey')),
                          selector=dict(mode='markers'))
        fig.update_layout(paper_bgcolor='#CFDBDF')
        fig.for_each_xaxis(lambda x: x.update(showticklabels=True))
    
        fig.show()
        fig.write_html(dst+'/'+'PlasticityIndex.html')
        
            # =========================GRADING=====================
    
        # create dataframe - link geology codes
        qry = """select GRAT.LOCA_ID, GRAT.SAMP_TOP, SAMP_TYPE, GRAT_SIZE, 
            GRAT_PERP, GEOL_GEOL 
            from GRAT left join GEOL ON GRAT.LOCA_ID = GEOL.LOCA_ID 
            where SAMP_TOP >= GEOL_TOP and SAMP_TOP < GEOL_BASE 
            order by GEOL_GEOL"""
        
        df = pd.read_sql_query(qry, conn)
        feedback.pushInfo(f"Result = {df}")
        
       
        lst_GEOL_GEOL = df['GEOL_GEOL'].unique()

        pio.templates.default = "plotly_white"
     
        # Create WC vs depth multi plots
        fig = px.line(
        df,
        x='GRAT_SIZE',
        y='GRAT_PERP',
        log_x=True,
        range_x=[0.001,200], 
        range_y=[0,100],
        height = 4000,
        facet_row = 'GEOL_GEOL',
        color = 'LOCA_ID',
        symbol = 'SAMP_TOP',
        labels={"GRAT_SIZE": "Particle size diameter (mm)",
                "GRAT_PERP": "Percent passing (%)",
                "GEOL_GEOL": "Code",
                "LOCA_ID": "EXPL Hole",
                "SAMP_TYPE":"Sample Type"},
        title="Particle size distribution by geology code (GEOL_GEOL)",
        markers=True,
        hover_data=["SAMP_TYPE"],
        )
        col = 1
        for row in range(1, len(lst_GEOL_GEOL)+1):
            # feedback.pushInfo(f"Row = {row}")
            # Major divisions
            fig.add_shape(type="line", x0=0.002, x1=0.002, y0=0, y1=100, 
                          xref=f'x{col}', yref=f'y{row}', 
                          line=dict(color="black", width=2))
            fig.add_shape(type="line", x0=0.06, x1=0.06, y0=0, y1=100, 
                          xref=f'x{col}', yref=f'y{row}', 
                          line=dict(color="black", width=2))
            fig.add_shape(type="line", x0=2, x1=2, y0=0, y1=100, 
                          xref=f'x{col}', yref=f'y{row}', 
                          line=dict(color="black", width=2))
            fig.add_shape(type="line", x0=60, x1=60, y0=0, y1=100, 
                          xref=f'x{col}', yref=f'y{row}', 
                          line=dict(color="black", width=2))
            #Minor divisions
            fig.add_shape(type="line", x0=0.006, x1=0.006, y0=0, y1=100, 
                          xref=f'x{col}', yref=f'y{row}', 
                          line=dict(color="black", width=1.5, dash="dash"))
            fig.add_shape(type="line", x0=0.02, x1=0.02, y0=0, y1=100, 
                          xref=f'x{col}', yref=f'y{row}', 
                          line=dict(color="black", width=1.5, dash="dash"))
            fig.add_shape(type="line", x0=0.2, x1=0.2, y0=0, y1=100, 
                          xref=f'x{col}', yref=f'y{row}', 
                          line=dict(color="black", width=1.5, dash="dash"))
            fig.add_shape(type="line", x0=0.6, x1=0.6, y0=0, y1=100, 
                          xref=f'x{col}', yref=f'y{row}', 
                          line=dict(color="black", width=1.5, dash="dash"))
            fig.add_shape(type="line", x0=6, x1=6, y0=0, y1=100, 
                          xref=f'x{col}', yref=f'y{row}', 
                          line=dict(color="black", width=1.5, dash="dash"))
            fig.add_shape(type="line", x0=20, x1=20, y0=0, y1=100, 
                          xref=f'x{col}', yref=f'y{row}', 
                          line=dict(color="black", width=1.5, dash="dash"))
            

        # fig.update_layout(xaxis_range=[0.001,2])
        # fig.update_layout(yaxis_range=[0,100])
        fig.update_layout(showlegend=True)
        fig.update_xaxes(showgrid=True, gridwidth=1, gridcolor='DarkGray')
        fig.update_yaxes(showgrid=True, gridwidth=1, gridcolor='DarkGray')
        fig.update_traces(marker=dict(size=4,
                                  line=dict(width=2,
                                            color='DarkSlateGrey')),
                      selector=dict(mode='markers'))
        fig.update_layout(paper_bgcolor='#CFDBDF')
        fig.for_each_xaxis(lambda x: x.update(showticklabels=True))


        fig.show()
        fig.write_html(dst+'/'+'ParticleSizeDistribution.html')
        
            # ========data tables===========
        # TODO put in loop - read json?
        lst_tables =[]
        table_title = "Summary table of Geology by GEOL_GEOL"
        qry = """select GEOL_GEOL, min(GEOL_TOP) as [minimum top depth], 
        max(GEOL_TOP) as [maximum top depth], min(GEOL_BASE) as 
        [minimum base depth], max(GEOL_BASE) as [maximum base depth] from GEOL 
        group by GEOL_GEOL"""
        
        df = pd.read_sql_query(qry, conn)
        df = df.replace(np.nan, "-")
        html_table = df.to_html(index=False)

        lst_tables.append('<h3>'+ table_title +'</h3>'+ html_table)
        # =================
        table_title = "Table of all Samples and geology code"
        qry = """select SAMP.LOCA_ID, SAMP_TOP, SAMP_BASE, SAMP_TYPE, SAMP_REF,
        SAMP_RECV, GEOL_GEOL from SAMP 
        left join GEOL on SAMP.LOCA_ID = GEOL.LOCA_ID 
        where SAMP_TOP >= GEOL_TOP AND SAMP_TOP < GEOL_BASE"""
        
        df = pd.read_sql_query(qry, conn)
        df = df.replace(np.nan, "-")
        html_table = df.to_html(index=False)

        lst_tables.append('<h3>'+ table_title +'</h3>'+ html_table)
       
        str_tables = '+'.join(lst_tables)
        html_content = ("<style>table{border-collapse:collapse;width:60%}td,\
                        th{text-align:left;padding:8px}tr:nth-child(even) \
                        {background-color:#CFDBDF}</style><p>"+str_tables+ \
                        "</table>")


        with open(dst+'/'+'tables.html', 'w') as f:
            f.write(html_content )
        webbrowser.open_new_tab(dst+'/'+'tables.html')
        
        conn.close()
    
        # End loop
        # TODO save database with plots for completeness?
    
        if feedback.isCanceled():
            return {}

        return {}

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'AGS Summary Plots'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'AGS data visualisation'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return ags_data_summry_plotsAlgorithm()
